name: zy
channels:
  - defaults
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - conda-pack=0.8.1
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - agentlace==0.1.3
      - aiofiles==25.1.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - array-record==0.8.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - blinker==1.9.0
      - can==0.0.0
      - casadi==3.7.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - chex==0.1.90
      - click==8.3.0
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - distlib==0.4.0
      - distrax==0.1.5
      - dm-env==1.6
      - dm-robotics-transformations==0.10.0
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - easyhid==0.0.10
      - einops==0.8.1
      - embreex==2.17.7.post7
      - envlogger==1.2
      - etils==1.13.0
      - exceptiongroup==1.3.0
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - flask==3.1.2
      - flatbuffers==25.9.23
      - flax==0.10.7
      - fonttools==4.60.1
      - franka-sim==0.0.1
      - fsspec==2025.10.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==1.2.2
      - h11==0.16.0
      - h5py==3.15.1
      - hidapi==0.15.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanize==4.14.0
      - identify==2.6.15
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jax==0.6.2
      - jax-cuda12-pjrt==0.6.2
      - jax-cuda12-plugin==0.6.2
      - jax-dataclasses==1.6.2
      - jaxlib==0.6.2
      - jaxlie==1.5.0
      - jaxls==0.0.0
      - jaxtyping==0.3.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - loguru==0.7.3
      - lxml==6.0.2
      - lz4==4.4.5
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - mujoco==2.3.7
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.15.1.9
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.7
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.4.5
      - openarm-can==1.1.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optree==0.17.0
      - orbax-checkpoint==0.11.30
      - oxe-envlogger==0.0.2
      - packaging==25.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pre-commit==3.3.3
      - proglog==0.1.12
      - promise==2.3
      - protobuf==4.21.12
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pycollada==0.9.2
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyrealsense2==2.56.5.9235
      - pyroki==0.0.0
      - pyspacemouse==1.1.5
      - python-can==4.6.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - robot-descriptions==1.21.0
      - rpds-py==0.28.0
      - rtree==1.4.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.44.0
      - serl-launcher==0.1.3
      - shapely==2.1.2
      - shellingham==1.5.4
      - shtab==1.7.2
      - simple-parsing==0.1.7
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - svg-path==7.0
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.1
      - tensorflow-datasets==4.9.9
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.78
      - termcolor==3.2.0
      - tf-keras==2.19.0
      - tfds-nightly==4.9.9.dev202510250044
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - toolz==1.1.0
      - tqdm==4.67.1
      - treescope==0.1.10
      - trimesh==4.9.0
      - typeguard==4.4.4
      - typer==0.20.0
      - typing==3.7.4.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - urllib3==2.5.0
      - vhacdx==0.0.9
      - virtualenv==20.35.4
      - viser==1.0.15
      - wadler-lindig==0.1.7
      - wandb==0.23.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yourdfpy==0.0.58
      - zipp==3.23.0
      - zmq==0.0.0
prefix: /home/peter/miniconda3/envs/zy
