orientation:
  w: 0.9744293921604402
  x: 0.01985842914280248
  y: -0.076685649388141
  z: -0.21026724343971034
position:
  x: -0.08509585789641119
  y: 0.033316270898601834
  z: -0.036466880027134274
