orientation:
  w: 0.9852279990694115
  x: -0.03606778227577441
  y: -0.09900560106558928
  z: 0.13499183637921428
position:
  x: -0.08238143520608354
  y: -0.03990346127623851
  z: -0.037379679576967396
