lift_joint_name: body_lift_joint
sim_init_joint_deg:
  # arm
  openarm_left_joint1: 0.0
  openarm_left_joint2: 0.0
  openarm_left_joint3: 0.0
  openarm_left_joint4: 1.5
  openarm_left_joint5: 0.0
  openarm_left_joint6: 0.0
  openarm_left_joint7: 0.0
  # hand
  # openarm_left_finger_joint1: 0.0
  # openarm_left_finger_joint2: 0.0
  # openarm_left_hand_tcp_joint1: 0.0

  # arm
  openarm_right_joint1: 0.0
  openarm_right_joint2: 0.0
  openarm_right_joint3: 0.0
  openarm_right_joint4: 1.5
  openarm_right_joint5: 0.0
  openarm_right_joint6: 0.0
  openarm_right_joint7: 0.0
  # hand
  # openarm_right_finger_joint1: 0.0
  # openarm_right_finger_joint2: 0.0
  # openarm_right_hand_tcp_joint1: 0.0

visualize_collision: true